package net.nennneko5787.lepus.gradle

import java.io.File
import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import org.gradle.api.tasks.options.Option

/**
 * Generates the `docs/compatibility` tables from the ledger.
 *
 * Committed rather than published, so it renders on GitHub without a Pages build, and the task
 * FAILS when the checked-in output is stale — the same discipline as committed generated code.
 * Run with `--write` to regenerate.
 *
 * A percentage with no fidelity notes behind it would be marketing. The notes are the point.
 */
abstract class SpecReportTask : DefaultTask() {

    @get:InputDirectory
    abstract val specDir: DirectoryProperty

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    private var write = false

    @Option(option = "write", description = "Rewrite the generated tables instead of checking them.")
    fun setWrite(value: Boolean) {
        write = value
    }

    private val statusOrder = listOf("implemented", "partial", "stub", "unsupported", "wontfix")

    @TaskAction
    fun report() {
        val spec = specDir.get().asFile
        val out = outputDir.get().asFile
        val shards = CoverageLoader.loadAll(spec.resolve("coverage"))

        val generated = mutableMapOf<String, String>()
        generated["summary.md"] = renderSummary(shards)
        shards.forEach { generated["${it.domain}.md"] = renderShard(it) }

        if (write) {
            out.mkdirs()
            generated.forEach { (name, content) ->
                out.resolve(name).writeText(content)
            }
            logger.lifecycle("specReport: wrote ${generated.size} file(s) to ${out.path}")
            return
        }

        val stale = generated.filter { (name, content) ->
            val file = out.resolve(name)
            !file.isFile || normalise(file.readText()) != normalise(content)
        }
        if (stale.isNotEmpty()) {
            throw org.gradle.api.GradleException(
                buildString {
                    appendLine("specReport: ${stale.size} generated file(s) are stale:")
                    stale.keys.sorted().forEach { appendLine("  docs/compatibility/$it") }
                    appendLine()
                    appendLine("Run `./gradlew specReport --write` and commit the result.")
                }
            )
        }
        logger.lifecycle("specReport: generated tables are up to date.")
    }

    private fun normalise(text: String) = text.replace("\r\n", "\n").trimEnd()

    private fun renderSummary(shards: List<CoverageShard>): String = buildString {
        appendLine("# Compatibility summary")
        appendLine()
        appendLine("<!-- GENERATED by ./gradlew specReport --write - do not edit. -->")
        appendLine()
        appendLine("Every Bedrock feature identifier Lepus knows about, and what it does with it.")
        appendLine("Definitions are normative in [SC-000 section 3](../../spec/normative/SC-000-conventions.md).")
        appendLine()

        val all = shards.flatMap { it.entries }
        appendLine("**${all.size} tracked feature identifiers across ${shards.size} domains.**")
        appendLine()
        appendLine("| Domain | Spec | Total | " + statusOrder.joinToString(" | ") + " |")
        appendLine("|---|---|--:|" + statusOrder.joinToString("") { "--:|" })
        for (shard in shards.sortedBy { it.domain }) {
            val counts = statusOrder.map { s -> shard.entries.count { it.status == s } }
            appendLine(
                "| [${shard.domain}](${shard.domain}.md) | ${shard.spec} | " +
                    "${shard.entries.size} | " + counts.joinToString(" | ") + " |"
            )
        }
        val totals = statusOrder.map { s -> all.count { it.status == s } }
        appendLine("| **total** | | **${all.size}** | " + totals.joinToString(" | ") { "**$it**" } + " |")
        appendLine()

        appendLine("## How to read this")
        appendLine()
        appendLine("| Status | Meaning |")
        appendLine("|---|---|")
        appendLine("| `implemented` | indistinguishable from Bedrock across everything the conformance corpus covers |")
        appendLine("| `partial` | works for the common case; the fidelity note says exactly where it does not |")
        appendLine("| `stub` | recognised and parsed, no runtime effect, emits a diagnostic |")
        appendLine("| `unsupported` | not implemented yet, deliberately |")
        appendLine("| `wontfix` | will not be implemented; the note says why |")
        appendLine()
        appendLine("A `stub` is not a bug report. It means Lepus reads the feature, tells you it")
        appendLine("cannot act on it, and keeps going - constitution rule 1.")
    }

    private fun renderShard(shard: CoverageShard): String = buildString {
        appendLine("# ${shard.domain}")
        appendLine()
        appendLine("<!-- GENERATED by ./gradlew specReport --write - do not edit. -->")
        appendLine()
        appendLine("Specification: [${shard.spec}](../../spec/normative/) &middot; ")
        appendLine("Ledger: [`spec/coverage/${shard.domain}.yaml`](../../spec/coverage/${shard.domain}.yaml)")
        appendLine()
        appendLine("| Feature | Status | Notes |")
        appendLine("|---|---|---|")
        for (entry in shard.entries) {
            val note = (entry.fidelity ?: entry.notes ?: "").replace("\n", " ").replace("|", "\\|")
            appendLine("| `${entry.id}` | ${entry.status} | $note |")
        }
    }
}
