package net.nennneko5787.lepus.core.registry;

import java.util.Map;
import java.util.Optional;
import net.nennneko5787.lepus.core.api.SpecImpl;

/**
 * What Bedrock's internal short name for a vanilla thing is called in Java. SC-120 §2.
 *
 * <p>A pack renaming or retexturing a vanilla item writes <b>Bedrock's</b> spelling —
 * {@code item.totem.name}, {@code tile.stone.stone.name} — where Java spells the same two things
 * {@code totem_of_undying} and {@code stone}. The identifiers themselves already agree; it is these
 * short names, used only inside language files and texture paths, that do not.
 *
 * <p><b>Not a guess and not a hand-written list.</b> The table is generated by
 * {@code ./gradlew generateBedrockConstants} from the pinned upstream snapshot, joined on the
 * English display name, and kept only where that name is unique in both games. 525 of its 1,443
 * entries have different spellings on the two sides, so treating the short name as the Java path
 * would be wrong for more than a third of them — including {@code wool.white}, which is
 * {@code white_wool}.
 *
 * <p><b>What is absent is absent on purpose.</b> Bedrock has one {@code banner_pattern} and Java has
 * nine items called "Banner Pattern"; no rule here can say which, so none of them are here and such
 * an item keeps its vanilla name. Refusing leaves a pack's rename unapplied, where choosing would
 * rename the wrong item — and this project has already paid for fitted constants once.
 *
 * <p>Sibling of {@link IdMapper}, which answers the other identity question: that one derives a
 * logical identifier for content a pack <i>brings</i>, this one recognises content that was already
 * there. Neither has a coverage entry, because neither is a Bedrock feature.
 */
@SpecImpl("SC-120")
public final class BedrockVanillaNames {

    /** Where the generated table is served from. Committed, so the build works offline. */
    private static final String RESOURCE = "/lepus/vanilla-names.tsv";

    private static final Map<String, String> BY_SHORT_NAME =
            TableResource.load(BedrockVanillaNames.class, RESOURCE);

    private BedrockVanillaNames() {
    }

    /**
     * Java's translation key for one of Bedrock's short names, or empty when there is no safe
     * answer.
     *
     * <p>The whole key, because which prefix it carries is not derivable: Java names a block's item
     * form under {@code block.minecraft.} and everything else under {@code item.minecraft.}, so a
     * caller renaming white wool needs the first and a caller assuming {@code item.} renames
     * nothing.
     *
     * @param shortName what stands between {@code item.}/{@code tile.} and {@code .name} in a
     *                  Bedrock language file — {@code totem}, {@code stone.stone}, {@code wool.white}
     */
    public static Optional<String> javaLangKeyOf(String shortName) {
        return shortName == null ? Optional.empty()
                : Optional.ofNullable(BY_SHORT_NAME.get(shortName));
    }

    /** The item's path alone, for the callers naming a texture rather than a translation. */
    public static Optional<String> javaPathOf(String shortName) {
        return javaLangKeyOf(shortName).map(key -> key.substring(key.lastIndexOf('.') + 1));
    }

    /**
     * Java's translation key for a whole Bedrock one, or empty.
     *
     * <p>Takes the whole key so that callers do not each re-derive which prefixes count.
     * {@code item.} and {@code tile.} both do: a block's item form is {@code tile.} in Bedrock, and
     * reading only the first lost every door and sign.
     */
    public static Optional<String> javaLangKeyOfBedrockKey(String key) {
        if (key == null || !key.endsWith(".name")) {
            return Optional.empty();
        }
        String body = key.substring(0, key.length() - ".name".length());
        if (body.startsWith("item.")) {
            return javaLangKeyOf(body.substring("item.".length()));
        }
        return body.startsWith("tile.")
                ? javaLangKeyOf(body.substring("tile.".length()))
                : Optional.empty();
    }

    /** How many names are known. Zero is a broken build, not a broken pack. */
    public static int size() {
        return BY_SHORT_NAME.size();
    }

}
