package net.nennneko5787.lepus.core.registry;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Optional;
import net.nennneko5787.lepus.core.api.SpecImpl;

/**
 * What Bedrock's internal short name for a vanilla thing is called in Java. SC-120 §2.
 *
 * <p>A pack renaming or retexturing a vanilla item writes <b>Bedrock's</b> spelling —
 * {@code item.totem.name}, {@code tile.stone.stone.name} — where Java spells the same two things
 * {@code totem_of_undying} and {@code stone}. The identifiers themselves already agree; it is these
 * short names, used only inside language files and texture paths, that do not.
 *
 * <p><b>Not a guess and not a hand-written list.</b> The table is generated by
 * {@code ./gradlew generateBedrockConstants} from the pinned upstream snapshot, joined on the
 * English display name, and kept only where that name is unique in both games. 525 of its 1,443
 * entries have different spellings on the two sides, so treating the short name as the Java path
 * would be wrong for more than a third of them — including {@code wool.white}, which is
 * {@code white_wool}.
 *
 * <p><b>What is absent is absent on purpose.</b> Bedrock has one {@code banner_pattern} and Java has
 * nine items called "Banner Pattern"; no rule here can say which, so none of them are here and such
 * an item keeps its vanilla name. Refusing leaves a pack's rename unapplied, where choosing would
 * rename the wrong item — and this project has already paid for fitted constants once.
 *
 * <p>Sibling of {@link IdMapper}, which answers the other identity question: that one derives a
 * logical identifier for content a pack <i>brings</i>, this one recognises content that was already
 * there. Neither has a coverage entry, because neither is a Bedrock feature.
 */
@SpecImpl("SC-120")
public final class BedrockVanillaNames {

    /** Where the generated table is served from. Committed, so the build works offline. */
    private static final String RESOURCE = "/lepus/vanilla-names.tsv";

    private static final Map<String, String> BY_SHORT_NAME = load();

    private BedrockVanillaNames() {
    }

    /**
     * The Java path for one of Bedrock's short names, or empty when there is no safe answer.
     *
     * @param shortName what stands between {@code item.}/{@code tile.} and {@code .name} in a
     *                  Bedrock language file — {@code totem}, {@code stone.stone}, {@code wool.white}
     */
    public static Optional<String> javaPathOf(String shortName) {
        return shortName == null ? Optional.empty()
                : Optional.ofNullable(BY_SHORT_NAME.get(shortName));
    }

    /**
     * The Java path a Bedrock language key names, or empty.
     *
     * <p>Takes the whole key so that callers do not each re-derive which prefixes count.
     * {@code item.} and {@code tile.} both do: a block's item form is {@code tile.} in Bedrock and
     * {@code block.minecraft.} in Java, and reading only the first lost every door and sign.
     */
    public static Optional<String> javaPathOfLangKey(String key) {
        if (key == null || !key.endsWith(".name")) {
            return Optional.empty();
        }
        String body = key.substring(0, key.length() - ".name".length());
        if (body.startsWith("item.")) {
            return javaPathOf(body.substring("item.".length()));
        }
        return body.startsWith("tile.")
                ? javaPathOf(body.substring("tile.".length()))
                : Optional.empty();
    }

    /** How many names are known. Zero is a broken build, not a broken pack. */
    public static int size() {
        return BY_SHORT_NAME.size();
    }

    /**
     * Reads the generated table.
     *
     * <p>An unreadable or absent table leaves this empty rather than throwing. Nothing here is
     * required for an add-on to load — a pack whose rename cannot be resolved keeps the vanilla
     * name, which is the same outcome as a name this table never knew.
     */
    private static Map<String, String> load() {
        Map<String, String> out = new LinkedHashMap<>();
        try (InputStream in = BedrockVanillaNames.class.getResourceAsStream(RESOURCE)) {
            if (in == null) {
                return Map.of();
            }
            BufferedReader reader =
                    new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8));
            String line;
            while ((line = reader.readLine()) != null) {
                if (line.isEmpty() || line.charAt(0) == '#') {
                    continue;
                }
                int tab = line.indexOf('\t');
                if (tab > 0 && tab < line.length() - 1) {
                    out.put(line.substring(0, tab), line.substring(tab + 1));
                }
            }
        } catch (IOException unreadable) {
            return Map.of();
        }
        return Collections.unmodifiableMap(out);
    }
}
