package net.nennneko5787.lepus.core.registry;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Reads a two-column table generated by {@code ./gradlew generateBedrockConstants}.
 *
 * <p>Shared by the two tables so that neither can drift into reading the format differently — they
 * are written by one task, and a second copy of "skip the comments, split on the tab" is a place for
 * them to disagree.
 *
 * <p>An unreadable or absent table is empty rather than an exception. Nothing here is required for
 * an add-on to load: a name or picture that cannot be resolved leaves the vanilla one in place,
 * which is the same outcome as an entry the table never had.
 */
final class TableResource {

    private TableResource() {
    }

    static Map<String, String> load(Class<?> owner, String resource) {
        Map<String, String> out = new LinkedHashMap<>();
        try (InputStream in = owner.getResourceAsStream(resource)) {
            if (in == null) {
                return Map.of();
            }
            BufferedReader reader =
                    new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8));
            String line;
            while ((line = reader.readLine()) != null) {
                if (line.isEmpty() || line.charAt(0) == '#') {
                    continue;
                }
                int tab = line.indexOf('\t');
                if (tab > 0 && tab < line.length() - 1) {
                    out.put(line.substring(0, tab), line.substring(tab + 1));
                }
            }
        } catch (IOException unreadable) {
            return Map.of();
        }
        return Collections.unmodifiableMap(out);
    }
}
